Language: python

jobs:
  include:

    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services:
        - docker
        
    - os: osx
      language: shell

env:
  global:
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to an API token in Travis settings
    - CIBW_BEFORE_BUILD="python3 -m pip --version && python3 -m pip install -U pip && python3 -m pip --version && python3 -m pip install -U cython && python3 -m pip uninstall -y numpy && python3 -m pip uninstall -y numpy && python3 -m pip uninstall -y numpy && python3 -m pip uninstall -y numpy && python scripts/install_numpy.py && python -c 'import numpy as np ; print(np.__version__)' "
    - CIBW_BUILD_VERBOSITY=3
    - CIBW_BUILD="cp3?-*x86_64"
    - CIBW_SKIP="cp33-* cp34-* cp35-*"
        
install:
  - python3 -m pip install -U pip numpy
  - python3 -m easy_install -U setuptools
  - python3 -m pip install pytest-cov
  - python3 -m pip install cython
  - python3 -m pip install cibuildwheel==1.5.1

script:
  - python3 setup.py build_ext -i
  - python3 -m pip install .
  - py.test --cov=pixell pixell/tests/ -s
  - find . -type f -iname '*.so' -print -delete
  - rm -rf _deps/
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - |
    echo $TRAVIS_TAG
    pip install twine
    pip install -U twine
    twine check wheelhouse/*
    if [[ $TRAVIS_TAG ]]; then
      twine upload --verbose --skip-existing wheelhouse/*.whl
    fi
    
    
addons:
  apt_packages:
  - gfortran
